# Usa uma imagem base Python slim (menor e mais segura)
FROM python:3.10-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o arquivo de requisitos e instala as dependências
# Isso aproveita o cache do Docker se apenas o código mudar
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante dos arquivos do projeto (seu código, incluindo app.py)
COPY . .

# Comando para rodar a aplicação
CMD ["python", "app.py"]